Meet magisk installer module temp

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,242 +1,151 @@
 #!/sbin/sh
-###FeraLab###
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false;
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
-TMPDIR=/dev/tmp;
-INSTALLER=$TMPDIR/install;
-MAGISKBIN=/data/adb/magisk;
-OUTFD=$2
-ZIP=$3
-set -o pipefail;
-umask 022;
-rm -rf $TMPDIR 2>/dev/null;
-mkdir -p $INSTALLER;
-ui_print() {
-  $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
-}
+
+TMPDIR=/dev/tmp
+MOUNTPATH=/dev/magisk_img
+
+# Default permissions
+umask 022
+
+# Initial cleanup
+rm -rf $TMPDIR 2>/dev/null
+mkdir -p $TMPDIR
+
+# echo before loading util_functions
+ui_print() { echo "$1"; }
+
 require_new_magisk() {
-  ui_print "*******************************";
-  ui_print " Please install Magisk v18.0+! ";
-  ui_print "*******************************";
-  exit 1;
+  ui_print "***********************************"
+  ui_print " Please install the latest Magisk! "
+  ui_print "***********************************"
+  exit 1
 }
-if [ -e /sys/fs/selinux/enforce ]; then
- chmod 666 /sys/fs/selinux/enforce;
- setenforce 0;
- echo "0" > /sys/fs/selinux/enforce;
- chmod 640 /sys/fs/selinux/enforce;
- chmod 440 /sys/fs/selinux/policy;
-fi;
-mount -o rw,remount /;
-mount -o rw,remount /data;
-mount -o rw,remount /cache;
-mount /;
-mount /data;
-mount /cache;
-mount /data 2>/dev/null;
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "  ";
-ui_print "*******************************";
-ui_print "         ***FeraLab***";
-ui_print "   FDE.AI by FeraVolt  2019";
-ui_print "*******************************";
-ui_print "FDE deploy...";
-ui_print ".";
-if [ -d /data/adb/magisk ]; then
- [ -f $MAGISKBIN/util_functions.sh ] || require_new_magisk;
- . $MAGISKBIN/util_functions.sh;
- $BOOTMODE && IMG=/data/adb/magisk_merge.img;
- MOUNTPATH=$TMPDIR/magisk_img;
- setup_flashable;
- mount_partitions > /dev/null 2>&1;
- api_level_arch_detect;
- $BOOTMODE && boot_actions || recovery_actions;
- ui_print "..";
- unzip -o "$ZIP" module.prop config.sh -d $INSTALLER > /dev/null 2>&1;
- . $INSTALLER/config.sh;
- MIN_VER="18000";
- MODID="FDE";
- MODPATH=$MOUNTPATH/$MODID;
- request_zip_size_check "$ZIP";
- mount_magisk_img > /dev/null 2>&1;
- rm -rf $MODPATH;
- mkdir -p $MODPATH;
- ui_print "...";
- unzip -o "$ZIP" 'system/*' -d $MODPATH > /dev/null 2>&1;
- rm -f $MODPATH/system/placeholder;
- for TARGET in $REPLACE; do
-  mktouch $MODPATH$TARGET/.replace;
- done;
- $AUTOMOUNT && touch $MODPATH/auto_mount;
- $PROPFILE;
- cp -af $INSTALLER/module.prop $MODPATH/module.prop;
- if $BOOTMODE; then
-  mktouch /sbin/.core/img/$MODID/update;
-  cp -af $INSTALLER/module.prop /sbin/.core/img/$MODID/module.prop;
- fi;
- ui_print "....";
- $LATESTARTSERVICE;
- {
-  echo "#!/system/bin/sh"
-  echo "   "
-  echo "if [ -e /system/etc/fde.ai/i.sh ]; then"
-  echo " /system/etc/fde.ai/i.sh;"
-  echo " rm -f /system/etc/fde.ai/i.sh;"
-  echo "fi;"
-  echo "/system/etc/fde.ai/busybox setsid /system/etc/fde.ai/r.sh > /dev/null 2>&1 &"
-  echo "   "
- } >> $MODPATH/service.sh;
- set_permissions;
- magisk --restorecon;
- ui_print ".....";
- sleep 1;
- unmount_magisk_img;
- umount /$MOUNTPATH;
- $BOOTMODE || recovery_cleanup;
- rm -rf $TMPDIR;
+
+imageless_magisk() {
+  [ $MAGISK_VER_CODE -gt 18100 ]
+  return $?
+}
+
+##########################################################################################
+# Environment
+##########################################################################################
+
+OUTFD=$2
+ZIPFILE=$3
+
+mount /data 2>/dev/null
+
+# Load utility functions
+if [ -f /data/adb/magisk/util_functions.sh ]; then
+  . /data/adb/magisk/util_functions.sh
+  NVBASE=/data/adb
 else
- mount -o rw /system;
- mount -o rw,remount /system;
- mount /system;
- if [ -d /system/engine ]; then
-  rm -Rf /system/engine;
-  rm -f /system/etc/fde;
-  rm -Rf /system/etc/init.d_fde_backup;
-  rm -f /system/xbin/fde;
-  rm -f /system/su.d/90fde.sh;
-  rm -f /system/etc/init.d/90fde;
-  rm -f /sdcard/Android/FDE_log.txt;
-  rm -f /sdcard/Android/FDE_config.txt;
-  rm -f /data/media/0/Android/FDE_config.txt;
-  rm -f /data/media/0/Android/FDE_log.txt;
- fi;
- rm -Rf /system/fde.ai;
- rm -Rf /system/etc/fde.ai;
- rm -Rf /system/engine;
- rm -f /system/etc/sysctl.conf;
- ui_print "..";
- unzip -o "$ZIP";
- ui_print "...";
- export PATH=/sbin:/system/sbin:/system/bin:/system/xbin:/system/vendor/bin:/su/xbin;
- if [ -e /data/su.img ]; then
-  mknod /dev/block/loop7 b 7 7;
-  losetup /dev/block/loop7 /data/su.img;
-  if [ ! -d /tmp ]; then
-   mkdir /tmp;
-  fi;
-  mount -t ext4 -o loop,noatime /dev/block/loop7 /tmp;
- fi;
- chmod -R 777 /system/etc/fde.ai;
- chmod 777 /system/etc/fde.ai/*;
- chmod 777 /system/etc/fde.ai/b/*;
- sleep 1;
- ui_print "....";
- if [ -e /init.supersu.rc ]; then
-  if [ ! -d /system/su.d ]; then
-  mkdir /system/su.d;
-  chmod 777 /system/su.d;
-  fi;
- fi;
- if [ -d /tmp/su.d ]; then
-  rm /tmp/su.d/99fde.sh;
-  touch /tmp/su.d/99fde.sh;
-  chmod 777 /tmp/su.d/99fde.sh;
-  {
-  echo "#!/system/bin/sh"
-  echo "   "
-  echo "if [ -e /system/etc/fde.ai/i.sh ]; then"
-  echo " /system/etc/fde.ai/i.sh;"
-  echo " rm -f /system/etc/fde.ai/i.sh;"
-  echo "fi;"
-  echo "/system/etc/fde.ai/busybox setsid /system/etc/fde.ai/r.sh > /dev/null 2>&1 &"
-  echo "   "
-  } >> /tmp/su.d/99fde.sh;
-  umount /tmp;
- elif [ -d /su/su.d ]; then
-  rm /su/su.d/99fde.sh;
-  touch /su/su.d/99fde.sh;
-  chmod 777 /su/su.d/99fde.sh;
-  {
-  echo "#!/system/bin/sh"
-  echo "   "
-  echo "if [ -e /system/etc/fde.ai/i.sh ]; then"
-  echo " /system/etc/fde.ai/i.sh;"
-  echo " rm -f /system/etc/fde.ai/i.sh;"
-  echo "fi;"
-  echo "/system/etc/fde.ai/busybox setsid /system/etc/fde.ai/r.sh > /dev/null 2>&1 &"
-  echo "   "
-  } >> /su/su.d/99fde.sh;
- elif [ -d /system/su.d ]; then
-  rm /system/su.d/99fde.sh;
-  touch /system/su.d/99fde.sh;
-  chmod 777 /system/su.d/99fde.sh;
-  {
-  echo "#!/system/bin/sh"
-  echo "   "
-  echo "if [ -e /system/etc/fde.ai/i.sh ]; then"
-  echo " /system/etc/fde.ai/i.sh;"
-  echo " rm -f /system/etc/fde.ai/i.sh;"
-  echo "fi;"
-  echo "/system/etc/fde.ai/busybox setsid /system/etc/fde.ai/r.sh > /dev/null 2>&1 &"
-  echo "   "
-  } >> /system/su.d/99fde.sh;
- elif [ -d /system/etc/init.d ]; then
-  if [ ! -d /system/etc/init.d_bak ]; then
-   mv /system/etc/init.d /system/etc/init.d_bak;
-   mkdir /system/etc/init.d;
-   chmod 777 /system/etc/init.d;
-  fi;
-  rm /system/etc/init.d/99fde;
-  rm /system/etc/init.d/99fde.sh;
-  touch /system/etc/init.d/99fde;
-  chmod 777 /system/etc/init.d/99fde;
-  {
-  echo "#!/system/bin/sh"
-  echo "   "
-  echo "if [ -e /system/etc/fde.ai/i.sh ]; then"
-  echo " /system/etc/fde.ai/i.sh;"
-  echo " rm -f /system/etc/fde.ai/i.sh;"
-  echo "fi;"
-  echo "/system/etc/fde.ai/busybox setsid /system/etc/fde.ai/r.sh > /dev/null 2>&1 &"
-  echo "   "
-  } >> /system/etc/init.d/99fde;
- elif [ -e /system/bin/debuggerd ]; then
-  if [ ! -e /system/bin/debuggerd_real ]; then
-   mv /system/bin/debuggerd /system/bin/debuggerd_real;
-   touch /system/bin/debuggerd;
-   chmod 755 /system/bin/debuggerd;
-   {
-  echo "#!/system/bin/sh"
-  echo "   "
-  echo "if [ -e /system/etc/fde.ai/i.sh ]; then"
-  echo " /system/etc/fde.ai/i.sh;"
-  echo " rm -f /system/etc/fde.ai/i.sh;"
-  echo "fi;"
-  echo "/system/etc/fde.ai/busybox setsid /system/etc/fde.ai/r.sh > /dev/null 2>&1 &"
-  echo "/system/bin/debuggerd_real;"
-  echo "   "
-   } >> /system/bin/debuggerd;
-  fi;
- fi;
- ui_print ".....";
- sleep 1;
- umount /system;
-fi;
-umount /data;
-umount /cache;
-ui_print "......";
-ui_print "Ready.";
-ui_print " ";
-ui_print " ";
-ui_print " ";
-sleep 1;
+  require_new_magisk
+fi
+
+# Preperation for flashable zips
+setup_flashable
+
+# Mount partitions
+mount_partitions
+
+# Detect version and architecture
+api_level_arch_detect
+
+# Setup busybox and binaries
+$BOOTMODE && boot_actions || recovery_actions
+
+##########################################################################################
+# Preparation
+##########################################################################################
+
+# Extract common files
+unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
+
+[ ! -f $TMPDIR/install.sh ] && abort "! Unable to extract zip file!"
+# Load install script
+. $TMPDIR/install.sh
+
+if imageless_magisk; then
+  $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
+  MODULEROOT=$NVBASE/$MODDIRNAME
+else
+  $BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
+  IMG=$NVBASE/$IMGNAME
+  request_zip_size_check "$ZIPFILE"
+  mount_magisk_img
+  MODULEROOT=$MOUNTPATH
+fi
+
+MODID=`grep_prop id $TMPDIR/module.prop`
+MODPATH=$MODULEROOT/$MODID
+
+print_modname
+
+ui_print "******************************"
+ui_print "Powered by Magisk (@topjohnwu)"
+ui_print "******************************"
+
+##########################################################################################
+# Install
+##########################################################################################
+
+# Create mod paths
+rm -rf $MODPATH 2>/dev/null
+mkdir -p $MODPATH
+
+# Remove placeholder
+rm -f $MODPATH/system/placeholder 2>/dev/null
+
+# Custom uninstaller
+[ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+
+# Auto Mount
+if imageless_magisk; then
+  $SKIPMOUNT && touch $MODPATH/skip_mount
+else
+  $SKIPMOUNT || touch $MODPATH/auto_mount
+fi
+
+# prop files
+$PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
+
+# Module info
+cp -af $TMPDIR/module.prop $MODPATH/module.prop
+if $BOOTMODE; then
+  # Update info for Magisk Manager
+  if imageless_magisk; then
+    mktouch $NVBASE/modules/$MODID/update
+    cp -af $TMPDIR/module.prop $NVBASE/modules/$MODID/module.prop
+  else
+    mktouch /sbin/.magisk/img/$MODID/update
+    cp -af $TMPDIR/module.prop /sbin/.magisk/img/$MODID/module.prop
+  fi
+fi
+
+# post-fs-data mode scripts
+$POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
+
+# service mode scripts
+$LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
+
+on_install
+
+# Handle replace folders
+for TARGET in $REPLACE; do
+  mktouch $MODPATH$TARGET/.replace
+done
+
+ui_print "- Setting permissions"
+set_permissions
+
+##########################################################################################
+# Finalizing
+##########################################################################################
+
+cd /
+imageless_magisk || unmount_magisk_img
+$BOOTMODE || recovery_cleanup
+rm -rf $TMPDIR $MOUNTPATH
+
+ui_print "- Done"
 exit 0
-
-
